Add links to everynoise playlists
Shinyhero36/Spicetify-Genre pull request #11
Opened 2022-08-02 06:37 UTC by sebastian-stubenvoll

This is a very naive implementation of the idea mentioned in #2, adding links to the everynoise genre playlists.

As far as I can tell you can't request the playlist link from everynoise.com directly (please let me know if I'm mistaken here), so this workaround uses the spotify `/search/` endpoint to look up the playlist by name. Results are checked to make sure the owner is the "Sounds of Spotify" account and the playlist name matches the correct genre. Successfully obtained playlists are stored in local storage.

The extra requests lead to slightly longer load times. A possible improvement would be to display the genres as soon as they are obtained and insert the links retroactively.

2022-08-02 17:02 UTC, Shinyhero36 commented
Thanks for your contribution.
I tried it and even with a slow internet connection the extra load time is not that long

2022-08-02 17:16 UTC, Shinyhero36 requested changes
This is good. I have suggested a few minor changes

2022-08-02 17:16 UTC, Shinyhero36 commented on genre.js
> +  const fetchPlaylist = async (genre) => {
You should rename the function to something like this
```javascript
const fetchSoundOfSpotifyPlaylist = async (genre) => {

2022-08-02 17:16 UTC, Shinyhero36 commented on genre.js
> +            const uri = await fetchPlaylist(genres[i]);
Rename the function as mentionned on the comment above

2022-08-02 17:16 UTC, Shinyhero36 commented on genre.js
> +  const fetchPlaylist = async (genre) => {
Try to add a docstring with a description, the parameter's type and the return type(s)

```javascript
/**
 * Fetch playlist from The Sound of Spotify for a given genre
 * @param {String} genre
 * @return {String|null}
 */

2022-08-03 08:07 UTC, sebastian-stubenvoll commented
Alrighty, adopted the changes you suggested :)

2022-08-03 08:42 UTC, Shinyhero36 approved these changes
Thanks

2022-08-03 08:42 UTC, merged